version: "3.9"

services:
  backend:
    build: ./backend
    container_name: infra-backend
    ports:
      - "5000:5000"
    networks:
      - infra-net

  frontend:
    build: ./frontend
    container_name: infra-frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - infra-net

networks:
  infra-net:
    driver: bridge
